config/routes.rb
Forem::Engine.routes.draw do
	resources :topics do
		resources :posts
	end
	root :to => "topics#index"
end

app/models/forem/post.rb
module Forem
  class Post < ActiveRecord::Base
  	belongs_to :topic, :counter_cache => true
    attr_accessible :text, :topic_id, :user_id, :user
    
    belongs_to :user, :class_name => Forem::Engine.user_class.to_s

  end
end

app/models/forem/topic.rb
module Forem
  class Topic < ActiveRecord::Base
		before_save :set_post_user

  	has_many :posts, :order => "created_at ASC"
    accepts_nested_attributes_for :posts

    has_one :last_post, :class_name => "Forem::Post",
                        :order => "created_at DESC"

    belongs_to :user, :class_name => Forem::Engine.user_class.to_s

    attr_accessible :subject, :user_id, :posts_attributes, :user

    private
    	def set_post_user
    		self.posts.first.user = self.user
    	end

  end
end

app/controllers/forem/application_controller.rb
module Forem
  class ApplicationController < ActionController::Base
  	
    private

    def authenticate_forem_user!
      if !current_user
        flash[:notice] = "You must be authenticated before you can do that."
        redirect_to main_app.sign_in_url
      end
    end
  end
end

app/controllers/forem/posts_controller.rb
require_dependency "forem/application_controller"

module Forem
  class PostsController < ApplicationController    
    before_filter :authenticate_forem_user!, :only => [:new, :create]
  	before_filter :find_topic

  	def new
  		@post = @topic.posts.build
  	end

  	def create
      params[:post].merge!(:user => current_user)
  		@post = @topic.posts.create(params[:post])
  		flash[:notice] = "Post has been created!"
  		redirect_to topic_path(@topic)
  	end

  	private

  	def find_topic
  		@topic = Forem::Topic.find(params[:topic_id])
  	end
  end
end

app/controllers/forem/topics_controller.rb
require_dependency "forem/application_controller"

module Forem
  class TopicsController < ApplicationController
    before_filter :authenticate_forem_user!, :only => [:new, :create]

  	def index
  		@topics = Forem::Topic.all
  	end

  	def new
  		@topic = Forem::Topic.new
  		@topic.posts.build
  	end

  	def create
      params[:topic].merge!(:user => current_user)
  		@topic = Forem::Topic.create(params[:topic])
  		flash[:notice] = "Topic has been created!"
  		redirect_to @topic
  	end

    def show
      @topic = Forem::Topic.find(params[:id])
    end

  end
end

app/helpers/forem/application_helper.rb
module Forem
  module ApplicationHelper
  end
end

app/helpers/forem/posts_helper.rb
module Forem
  module PostsHelper
  end
end

app/helpers/forem/topics_helper.rb
module Forem
  module TopicsHelper
  end
end

app/views/forem/posts/_form.html.erb
<p>
	<%= post.label :text %>
	<%= post.text_area :text %>
</p>

app/views/forem/posts/_post.html.erb
<%= div_for(post) do %>
	<small>Written at <%= post.created_at %></small>
	<small class='user'>By <%= post.user %></small>
	<%= simple_format(post.text) %>
	<%= link_to "Reply!", new_topic_post_path(@topic) %>
<% end %>

app/views/forem/posts/new.html.erb
<h2>New Post</h2>
<%= form_for [@topic, @post]  do |post| %>
	<%= render :partial => 'form', :locals => { :post => post } %>
	<%= post.submit %>
<% end %>

app/views/forem/topics/_form.html.erb
<%= form_for @topic do |f| %>
	<p>
		<%= f.label :subject %>
		<%= f.text_field :subject %>
	</p>
	<%= f.fields_for :posts do |post| %>
		<%= render :partial => "forem/posts/form", 
								:locals => { :post => post } %>
	<% end %>
	<%= f.submit %>
<% end %>

app/views/forem/topics/index.html.erb
<h1>Topics</h1>
<% if current_user %>
	<%= link_to "New Topic", new_topic_path %>
<% end %>
<% if @topics.empty? %>
	There are currently no topics.
<% else %>
	<table id='topics'>
		<thead>
			<tr>
				<td>Subject</td>
				<td>Post count</td>
				<td>Last post at</td>
			</tr>	
		</thead>
		<tbody>
			<% @topics.each do |topic| %>
				<tr>
					<td id='topic_subject'><%= link_to topic.subject, topic %></td>
					<td id='post_count'><%= topic.posts_count %></td>
					<td id='last_post'>
							last post was <%= time_ago_in_words(topic.last_post.created_at) %> ago by <%= topic.last_post.user %>
					</td>
				</tr>	
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/forem/topics/new.html.erb
<h1>New Topic</h1>
<%= render "form" %>

app/views/forem/topics/show.html.erb
<%= div_for @topic do %>
	<h1><%= @topic.subject %></h1>
		<div id='posts'>
			<%= render :partial => "forem/posts/post", 
									:collection => @topic.posts %>
		</div>
<% end %>

app/views/layouts/forem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forem</title>
  <%= stylesheet_link_tag    "forem/application", :media => "all" %>
  <%= javascript_include_tag "forem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, message| %>
		<div id='flash_<%= key%>'><%= message %></div>
	<% end %>
<%= yield %>

</body>
</html>